### ISSUE TITLE
k5_auth not taking module params and authenticating

### ISSUE THREAD

**Issue by mohclips** [mohclips/k5-ansible-infra#1]
If just setting the module params you cannot auth, but setting the env vars works fine

`fatal: [localhost]: FAILED! => {"changed": false, "debug": [], "failed": true, "msg": "RESP: HTTP Code:401 {\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"}
`

`- k5_auth:
    username: "{{ username }}"
    password: "{{ password }}"
    project_id: "{{ proj }}"
    user_domain: "{{domain }}"
    region_name: "uk-1"
  register: k5_auth_reg`

from Kenny Brown - ta fella. :)

**Comment by KennyBrown1** [comment]
I found the actual cause of this problem and it turned out to be not related to passing the parameters.

In the k5_auth.py file, line 295 is looking for 'X-Subject-Token' in the response.headers.keys. In our solution the response from K5 was all in lowercase. Changing the 'X-Subject-Token' entries to 'x-subject-token' allowed the authentication process to complete using the module params

**Comment by mohclips** [comment]
That's interesting.  can you run this code a few times please, so we can see what the raw response is.

`curl -i -s -X POST -H "Content-Type: application/json" -d '{ "auth": {"identity": {"methods": ["password"],"password": {"user": {"name": "'$OS_USERNAME'","domain": { "name": "'$OS_USER_DOMAIN_NAME'" },"password": "'$OS_PASSWORD'"}}},"scope": {"project": {"id": "'$OS_PROJECT_ID'"}}}}' https://identity.$OS_REGION_NAME.cloud.global.fujitsu.com/v3/auth/tokens | grep -i x-subject-token
`
all one line.

should come back like this.  Which is case senstive.
`X-Subject-Token: 76a29bedd8084507936489bc32036791`

**Comment by KennyBrown1** [comment]
Hi

I have run the command as requested and it did return the case you expected:
X-Subject-Token: 3c40d160a0e940a1adec5fb61e2c1a99

In the k5_auth.py file I modified the 'if X-Subject-Token' statement to dump out response.headers.keys on failure and it returned the x-subject-token in lower case:
'x-subject-token': '192ac5431c944851a2ee04b5a1ebe615'

Not sure why there is a difference.

**Comment by mohclips** [comment]
dictionary keys are case sensitive.   So some how `requests` is returning a lowercase key. very odd.

I guess the easiest fix is to `.lower()` the test case.   I'll have a look over the weekend.

**Comment by mohclips** [comment]
fixed.  I'm not sure how this happens, but a work around has been added.
