### ISSUE TITLE
Error when creating port using k5_port

### ISSUE THREAD

**Issue by KennyBrown1** [mohclips/k5-ansible-infra#3]
Hi

I have encountered an error when creating a port using k5_port. The port creates successfully but returns an error which relates to line 372 of the k5_port.py file. The error indicates that 'subnet' is not a valid return value. Sorry I don't have the exact error to hand.

I found that by changing 'subnet' to 'port' on this line fixed the issue.

**Comment by mohclips** [comment]
can you update to the latest version please. then retest.

**Comment by KennyBrown1** [comment]
Doh... Rookie mistake.... The latest version works ok

**Comment by mohclips** [comment]
ill close this then :)
